[package]
name = "balatro-rs"
version = "0.0.1"
edition = "2021"
description = "Game engine and move generator for simplified version of balatro"
license = "MIT"
repository ="https://github.com/evanofslack/balatro-rs"
keywords = ["balatro", "game-engine", "move-generator"]

[dependencies]
rand = "~0.8.5"
thiserror = "~1.0.61"
serde = { version = "~1.0.215", optional = true, features = ["derive"] }
serde_json = { version = "~1.0.118", optional = true }
tracing = { version = "~0.1.40", optional = true}
uuid  = {version = "~1.9.1", optional = true, features = ["v7"]}
itertools = "0.13.0"
indexmap = "2.6.0"
strum = { version = "0.26", features = ["derive"] }
pyo3 = {version = "0.24.1", optional = true}
colored = {version = "2.2.0", optional = true}

[dev-dependencies]
criterion = "0.3"

[features]
default = ["serde", "python"]
python = ["dep:pyo3"]
serde = ["dep:serde", "dep:serde_json", "uuid?/serde"]
colored = ["dep:colored"]

[[bench]]
name = "benchmark"
harness = false
