[package]
name = "pylatro"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pylatro"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.1"
balatro-rs = {path = "../core/", version = "0.0.1"}
